Final Project
Lisenok666/Avito pull request #10
Opened 2022-10-31 20:13 UTC by Lisenok666

Написал реализацию проекта
Сейчас время приготовления, доставки и самовывоза не зависят от пиццы
Нет тестов

2022-10-31 20:23 UTC, Lisenok666 commented
Решение в коммите [Without tets](https://github.com/Lisenok666/Avito/pull/10/commits/c69c6a3e678e472560f46451bff842e103181e14)

2022-11-21 18:34 UTC, ffix requested changes
Спасибо за решение! Есть проблемы, DoD не выполнен

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +    @correct_init
А зачем декоратор, почему не проверить сразу в init?

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +class pizza_recipe():
Нейминг класса не по pep8, должно быть UpperCamelCase

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +    picture = ' \N{winking face}: '
Хорошо бы придерживаться консистентности в использовании emoji, потому что где-то используется escape-последовательность, а где-то emoji как unicode символ.

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +def order(ctx, pizza: str, delivery: bool):
А как заказать пиццу иного размера?

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +delivery_alt = delivery
Не совсем понимаю что тут просиходит

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +        def wrapper(pizza):
параметр pizza не используется тут и в самих функциях

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +            return func
wrapper не вызывает функцию, а просто её возвращает. похоже, тут есть проблема

2022-11-21 18:34 UTC, ffix commented on python 5/cli.py
> +def menu(ctx):
Вызов menu не возвращает список:
```
python cli.py menu                                                                 ⎈ fancy-dakota/snninua
<bound method pizza_recipe.dict of <__main__.Margherita object at 0x10402aec0>>
<bound method pizza_recipe.dict of <__main__.Pepperoni object at 0x10402aec0>>
<bound method pizza_recipe.dict of <__main__.Hawaiian object at 0x10402aec0>>
```

2022-11-21 18:35 UTC, ffix requested changes

2022-11-21 18:35 UTC, ffix commented on python 5/cli.py
> +from random import randint
Импорты сгруппированы не по pep8: https://peps.python.org/pep-0008/#imports

2022-12-04 20:50 UTC, Lisenok666 commented on python 5/cli.py
> +    @correct_init
Вы правы, перенёс в init

2022-12-04 20:52 UTC, Lisenok666 commented on python 5/cli.py
> +class pizza_recipe():
Поправил

2022-12-04 20:55 UTC, Lisenok666 commented on python 5/cli.py
> +    picture = ' \N{winking face}: '
Исправил в новой версии

2022-12-04 20:55 UTC, Lisenok666 commented on python 5/cli.py
> +def order(ctx, pizza: str, delivery: bool):
Добавил параметр big_size

2022-12-04 20:56 UTC, Lisenok666 commented on python 5/cli.py
> +def menu(ctx):
Исправил, забыл добавить () после dict(

2022-12-04 20:57 UTC, Lisenok666 commented on python 5/cli.py
> +class pizza_recipe():
в коммите fix_naming

2022-12-04 20:58 UTC, Lisenok666 commented on python 5/cli.py
> +delivery_alt = delivery
в order у меня есть переменная delivery из-за чего при вызове функции delivery(pizza) питон ругается

2022-12-04 20:58 UTC, Lisenok666 commented on python 5/cli.py
> +        def wrapper(pizza):
Переделал wrapper

2022-12-04 20:59 UTC, Lisenok666 commented
Прошу прощения, что залил несколько коммитов из-за чего сложнее будет проверять
Финальная версия в последнем коммите)

2022-12-31 14:34 UTC, Lisenok666 commented on python 5/cli.py
> +            return func
тут не отписался, но wrapper вызывает функции

2022-12-31 14:36 UTC, Lisenok666 commented on python 5/cli.py
> +from random import randint
тут тоже не отписался, но пробел был добавлен между импортами

2023-01-09 13:23 UTC, ffix commented on python 5/cli.py
> +from random import randint
Порядок всё ещё некорректный

2023-01-09 13:24 UTC, ffix commented on python 5/cli.py
> +            return func
Судя по коду, всё ещё не вызывает

2023-01-24 19:06 UTC, ffix approved these changes

2023-01-24 19:27 UTC, merged